// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "subscriptions/internal/graphql/graph/model"

	models "subscriptions/internal/domain"
)

// CommentInterface is an autogenerated mock type for the CommentInterface type
type CommentInterface struct {
	mock.Mock
}

// CheckCommentId provides a mock function with given fields: ctx, comtId, postId
func (_m *CommentInterface) CheckCommentId(ctx context.Context, comtId *string, postId string) error {
	ret := _m.Called(ctx, comtId, postId)

	if len(ret) == 0 {
		panic("no return value specified for CheckCommentId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, string) error); ok {
		r0 = rf(ctx, comtId, postId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetComments provides a mock function with given fields: ctx, postId, first, after
func (_m *CommentInterface) GetComments(ctx context.Context, postId string, first *int32, after *string) (*[]models.Comment, string, bool, error) {
	ret := _m.Called(ctx, postId, first, after)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 *[]models.Comment
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *int32, *string) (*[]models.Comment, string, bool, error)); ok {
		return rf(ctx, postId, first, after)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *int32, *string) *[]models.Comment); ok {
		r0 = rf(ctx, postId, first, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *int32, *string) string); ok {
		r1 = rf(ctx, postId, first, after)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *int32, *string) bool); ok {
		r2 = rf(ctx, postId, first, after)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, *int32, *string) error); ok {
		r3 = rf(ctx, postId, first, after)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// SaveComment provides a mock function with given fields: ctx, c
func (_m *CommentInterface) SaveComment(ctx context.Context, c *model.Comment) (string, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for SaveComment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Comment) (string, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Comment) string); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Comment) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentInterface creates a new instance of CommentInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentInterface {
	mock := &CommentInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
