// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "subscriptions/internal/graphql/graph/model"

	postgres "subscriptions/internal/storage/postgres"

	posts "subscriptions/internal/services/posts"
)

// Post is an autogenerated mock type for the Post type
type Post struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, s
func (_m *Post) GetAll(ctx context.Context, s *postgres.Storage) ([]posts.Posts, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []posts.Posts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *postgres.Storage) ([]posts.Posts, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *postgres.Storage) []posts.Posts); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]posts.Posts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *postgres.Storage) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPost provides a mock function with given fields: ctx, s, id
func (_m *Post) GetPost(ctx context.Context, s *postgres.Storage, id string) (*posts.Posts, error) {
	ret := _m.Called(ctx, s, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 *posts.Posts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *postgres.Storage, string) (*posts.Posts, error)); ok {
		return rf(ctx, s, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *postgres.Storage, string) *posts.Posts); ok {
		r0 = rf(ctx, s, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*posts.Posts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *postgres.Storage, string) error); ok {
		r1 = rf(ctx, s, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SavePost provides a mock function with given fields: ctx, s, p
func (_m *Post) SavePost(ctx context.Context, s *postgres.Storage, p *model.Post) (string, error) {
	ret := _m.Called(ctx, s, p)

	if len(ret) == 0 {
		panic("no return value specified for SavePost")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *postgres.Storage, *model.Post) (string, error)); ok {
		return rf(ctx, s, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *postgres.Storage, *model.Post) string); ok {
		r0 = rf(ctx, s, p)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *postgres.Storage, *model.Post) error); ok {
		r1 = rf(ctx, s, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPost creates a new instance of Post. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPost(t interface {
	mock.TestingT
	Cleanup(func())
}) *Post {
	mock := &Post{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
