// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"postID"`
	Text      string    `json:"text"`
	ParentID  *string   `json:"parentID,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type CommentConnection struct {
	Edges       []*CommentEdge `json:"edges"`
	EndCursor   *string        `json:"endCursor,omitempty"`
	HasNextPage bool           `json:"hasNextPage"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type Mutation struct {
}

type Post struct {
	ID              string             `json:"id"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	CommentsAllowed bool               `json:"commentsAllowed"`
	Comments        *CommentConnection `json:"comments"`
	CreatedAt       time.Time          `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}
